package:
  name: fftw
  version: 3.3.5

source:
  fn: fftw-3.3.5.tar.gz
  md5: 6cc08a3b9c7ee06fdd5b9eb02e06f569
  url: http://www.fftw.org/fftw-3.3.5.tar.gz

requirements:
  build:
    - gcc

build:
  detect_binary_files_with_prefix: true
  

about:
  home: 'http://www.fftw.org/'
  license: GPL
  summary: "FFTW: Fastest Fourier Transform in the West"