# The language in this case has no bearing - we are going to be making use of "conda" for a
# python distribution for the scientific python stack.
language: c

os:
  - linux
  - osx

osx_image: xcode6.4

env:

    matrix:
        - PYTHON_VERSION=3.7
        - PYTHON_VERSION=3.6
        - PYTHON_VERSION=2.7
        - PYTHON_VERSION=3.5

    global:
        - DESTINATION_CONDA_CHANNEL="nickhand"
        - TARGET_ARCH="x64"
        - CONDA_INSTALL_LOCN="${HOME}/miniconda"

        # Defines BINSTAR_TOKEN for your binstar channel
        - secure: "uKz/H4eDc4Dd5ujHd1GYElOM7M7jy1Hfh3p7D2Qc3cZS45VtqNnvXn73QUXmk3cb6iJzYkME2WzyN+Cpr5c94zduTZLxusBfx1+wh/x3JXtwh+xz31k5GdJMKEFqvzynsTaloqhmt+Ak6holQ95zPA3RQ7oBtuMAO36zJ97WrxUVQxqma8oZ1LSMbMvC7YJgbtOZOqYY/30wza1QsPsv8QN0pHez7TpDp33wmi/3trcpsnkkfjAakow3P6hrsNoLFczIBC7yV6hFVi55R1tuniKY/IoJgLYIyQrJmVE4MYNuAYLb3b1PiHjTQcMoOxsdH4Wuhm2YI/LmEpFd+zXjJadeJC/+S+dEJN54usNqb224sAqKgZUBg9tXq23LVfAo5NEP3jV5ilMv3NUJZeVRaABUZz9Fu/EN+MkRJeSf3EiXA+FlZsXqSm2/NJDo0cHhOwxMia98x6QjNflD7P1gd3TE9+T91ojA3/yp6t63npNlPu//Uee8Vr/TwIMmy40E2Pc3kv4k2reZ17+ShF6zKgDSTUsP2rQ67u65VpQw2swXoS4Mgi0Rq95ylzXYJBiurHgUQ3Db08J4nlg8a/LNEORB5sR7yK6aPprIGYGySRuKdybvOMnJwdytRShumJJf0HaStxmyOqvAYMnDwvaLsWPaezWJG6+eSMqbuWA/NYY="

install:
    # Install and set up miniconda.
    - if [ $TRAVIS_OS_NAME == "linux" ]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
    - if [ $TRAVIS_OS_NAME == "osx" ]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
    - bash miniconda.sh -b -p $CONDA_INSTALL_LOCN
    - export PATH=${CONDA_INSTALL_LOCN}/bin:$PATH
    - conda config --set always_yes true

    - conda install --quiet conda

    # so we can grab compiled packages for dependencies
    - conda config --prepend channels nickhand
    - conda config --append channels bccp
    - conda config --append channels astropy
    - conda config --prepend channels defaults
    - conda config --append channels conda-forge # need for george dependencies

    # Install a couple of dependencies we need for sure.
    - conda install --quiet --yes astropy anaconda-client=1.6.2 jinja2 cython pycrypto
    - conda install ruamel_yaml

    # latest conda build
    - conda install conda-build

    # To ease debugging, list installed packages
    - conda info -a
    - conda list
    - |
      # Only upload if this is NOT a pull request.
      if [ "$TRAVIS_PULL_REQUEST" = "false" ] && \
         [ $TRAVIS_REPO_SLUG = "nickhand/pyRSD-conda-channel" ] && \
         [ "$TRAVIS_BRANCH" == "master" ]; then
          UPLOAD="--user $DESTINATION_CONDA_CHANNEL --token $BINSTAR_TOKEN";
          conda config --set anaconda_upload true
          echo "Uploading enabled";
      else
          echo "Uplading disabled";
          UPLOAD="";
      fi

script:
    - INSPECT="--skip-existing -c nickhand"
    - VARIANT=variants/python-${PYTHON_VERSION}.yaml
    - python extrude_recipes.py requirements.yml
    # Packages are uploaded as they are built.
    - bash build-all.sh -m $VARIANT $INSPECT $UPLOAD

after_success:
    # build the documentation
    - curl -X POST https://readthedocs.org/build/pyrsd/latest
