{% set name = "george" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5}}

build:
  number : 0

requirements:
  build:
    - python
    - setuptools
    - eigen3
    - numpy
    - pybind11

  run:
    - python
    - setuptools
    - eigen3
    - numpy
    - scipy
    - pybind11

test:
  requires:
    - nose
  imports:
    - george
    - george.testing

about:
  home: https://github.com/dfm/george
  license:  MIT License
  summary: 'Blazingly fast Gaussian Processes for regression.'
