{% set name = "george" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5}}
  patches:
    # Applies a patch to fix gcc v4.8 compatibility issue.
    - gcc-4.8.diff

build:
  number : 0

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - pybind11
    - numpy x.x

  run:
    - python
    - setuptools
    - numpy x.x
    - scipy

test:
  imports:
    - george

about:
  home: https://github.com/dfm/george
  license:  MIT License
  summary: 'Blazingly fast Gaussian Processes for regression.'
