{% set name = "pyRSD" %}

package:
  name: pyrsd
  version: {{ version }}
source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5}}

build:
  number: 0
  script:
      - source /global/project/projectdirs/m779/nhand/Programs/source/pyRSD-conda-channel/nersc_profile.sh
      - export CC=gcc; export CXX=g++;
      - export LDFLAGS=-lgslcblas
      - export CFLAGS=-fPIC
      - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
  - python
  - numpy x.x
  - setuptools
  - gcc
  - gsl >=2.2.1
  - fftw
  - swig

  run:
  - python
  - libgcc
  - fftw
  - gsl >=2.2.1
  - numpy x.x
  - pandas
  - scipy
  - george
  - scikit-learn >=0.17
  - emcee
  - mpi4py-cray
  - matplotlib
  - seaborn
  - corner
  - six
  - lmfit >=0.9
  - autograd
  - astropy
  - xarray

test:
  imports:
  - pyRSD
  - pyRSD.rsd

about:
  home: http://github.com/nickhand/pyRSD
  license: GPL3
  summary: Anisotropic RSD Fourier space modeling in python
  license_family: GPL3

extra:
  recipe-maintainers:
  - nickhand
