{% set name = "pyRSD" %}

package:
  name: pyrsd
  version: {{ version }}
source:
  # fn: {{ name }}-{{ version }}.tar.gz
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # md5: {{ md5}}
  git_url: https://github.com/nickhand/pyRSD.git
  git_rev: master

build:
  number: 0

requirements:

  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'
    - '{{ compiler("fortran") }}'

  host:
    - python
    - numpy
    - setuptools
    - gsl >=2.2.1
    - fftw
    - swig

  run:
    - python
    - fftw
    - gsl >=2.2.1
    - '{{ pin_compatible("numpy") }}'
    - pandas
    - scipy
    - george >=0.3
    - scikit-learn >=0.17
    - emcee
    - mpi4py
    - matplotlib
    - seaborn
    - corner
    - six
    - lmfit >=0.9
    - autograd
    - astropy
    - xarray

test:
  imports:
  - pyRSD
  - pyRSD.rsd

about:
  home: http://github.com/nickhand/pyRSD
  license: GPL3
  summary: Anisotropic RSD Fourier space modeling in python
  license_family: GPL3

extra:
  recipe-maintainers:
  - nickhand
