{% set name = "fftw" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  md5: 6cc08a3b9c7ee06fdd5b9eb02e06f569
  url: http://www.fftw.org/fftw-{{ version }}.tar.gz

requirements:
  build:
    - '{{ compiler("c") }}'

build:
  detect_binary_files_with_prefix: true


about:
  home: 'http://www.fftw.org/'
  license: GPL
  summary: "FFTW: Fastest Fourier Transform in the West"
