{% set name = "george" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5}}
  patches:
    # Applies a patch to fix gcc v4.8 compatibility issue.
    - gcc-4.8.diff

build:
  number : 3
  script:
    - source $PROGRAMS_DIR/source/pyRSD-conda-channel/nersc_profile.sh
    - which gcc
    - gcc --version
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - gcc
    - setuptools
    - toolchain
    - pybind11
    - numpy x.x

  run:
    - python
    - setuptools
    - numpy x.x
    - scipy
    - pybind11

test:
  imports:
    - george

about:
  home: https://github.com/dfm/george
  license:  MIT License
  summary: 'Blazingly fast Gaussian Processes for regression.'
