{% set name = "george" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5}}

build:
  number : 3
  script:
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:

  build:
    - '{{ compiler("c") }}'
    - toolchain

  host:
    - python
    - setuptools
    - pybind11
    - numpy

  run:
    - python
    - setuptools
    - '{{ pin_compatible("numpy") }}'
    - scipy
    - pybind11

test:
  imports:
    - george

about:
  home: https://github.com/dfm/george
  license:  MIT License
  summary: 'Blazingly fast Gaussian Processes for regression.'
