package:
  name: pyrsd
  version: {{version}}
source:
  git_url: https://github.com/nickhand/pyRSD.git
  git_tag: master

build:
  number: 0
  script:
      - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
  - python
  - numpy
  - setuptools
  - gcc
  - gsl
  - fftw
  - swig

  run:
  - python
  - libgcc
  - fftw
  - gsl >=2.2.1
  - numpy
  - pandas
  - scipy
  - george
  - scikit-learn >=0.17
  - emcee
  - mpi4py
  - matplotlib
  - seaborn
  - corner
  - six
  - lmfit >=0.9
  - autograd
  - astropy

test:
  imports:
  - pyRSD
  - pyRSD.rsd

about:
  home: http://github.com/nickhand/pyRSD
  license: GPL3
  summary: Anisotropic RSD Fourier space modeling in python
  license_family: GPL3

extra:
  recipe-maintainers:
  - nickhand
